### PR TITLE
Fix links and parentheses don't work well together 

### LINKED ISSUE #78: Links and parentheses don't work well together
`([linkme](schema://domain/whees))` results in `(linkme` -> `schema://domain/whees)` where one would expect `(linkme)` -> `schema://domain/whees`.

This can be fixed by making the link regex not greedy. The downside is that embedded parentheses in links will not be parsed correctly. 

Another approach is to try to balance the bracket: any closing bracket at the end of the link that's is not matched by an opening bracket will be assumed to outside of the actual link. This heuristic seems to work well in practice. I've made a PR for this (https://github.com/bmoliveira/MarkdownKit/pull/79).

Before (notice how the first linkme is broken):
Screenshot 2021-02-02 at 22 49 34

After (notice how all links now work correctly):
Screenshot 2021-02-02 at 22 50 22

### PR DESCRIPTION
**Pull request by gaebel**
Continues #79, Fixes #78

Summary by @AndreasVerhoeven  
> - we count the number of opening and closing parentheses in the link
> - if we have more closing parentheses than opening parentheses
> - AND if there are closing parentheses at the end of the link, we assume they should originally have been outside of the link and be part of the regular text 
 
> This seems to work well in practice: Almost all links with parentheses have them balanced (e.g. wikipedia links), and links surrounded by () now work correctly as well

I've fixed the merge conflicts and changed the replaceDefault method to use generics

In addition to that:
- Fixes an issues with inline parentheses of the link text and url
- Adds https as scheme if it is missing

Planning to add:
- Ability to provide a default scheme

### CODE REVIEW

File: MarkdownKit/Sources/Common/Elements/Link/MarkdownLink.swift [hunk 1]
```diff
@@ -33,11 +33,13 @@ open class MarkdownLink: MarkdownLinkElement {
   
   open func formatText(_ attributedString: NSMutableAttributedString, range: NSRange,
                          link: String) {
-    guard let encodedLink = link.addingPercentEncoding(withAllowedCharacters: CharacterSet.urlHostAllowed)
+    let fullLink = link.starts(with: "http") ? link : "https://\(link)"
```
Comment (benjohnde) [inline MarkdownKit/Sources/Common/Elements/Link/MarkdownLink.swift:36]: Small question: what if the link does not contain either `http` or `https`?

**Review by benjohnde — COMMENTED** [review]
LGTM, just one small question arose during that review!

File: MarkdownKit/Sources/Common/Elements/Link/MarkdownLink.swift (hunk 1 above)
Comment (benjohnde) [reply MarkdownKit/Sources/Common/Elements/Link/MarkdownLink.swift:36]: Ouch, never mind! As you are checking for http it also includes https, phew!

**Comment by benjohnde** [comment]
Ah, never mind :) LGTM!
